name: Node.js CI (Continuous Run)

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:        # Manual trigger option

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Verify Owner Information
      run: |
        FIXED_URL="https://siam-the-frog-yml.vercel.app/owner.json"
        EXPECTED_OWNER="SiamTheFrog" 

        RESPONSE=$(curl -s $FIXED_URL)
        if [ $? -ne 0 ]; then
          echo "Error: Failed to fetch JSON from $FIXED_URL"
          exit 1
        fi

        ACTUAL_OWNER=$(echo $RESPONSE | jq -r '.owner')
        if [ "$ACTUAL_OWNER" != "$EXPECTED_OWNER" ]; then
          echo "Error: Owner verification failed. Expected '$EXPECTED_OWNER' but got '$ACTUAL_OWNER'."
          exit 1
        fi

        echo "================================="
        echo "This code is owned by $ACTUAL_OWNER"
        echo "================================="

    - name: Install Dependencies
      run: npm install

    - name: Start Application
      run: |
        echo "Starting Application..."
        npm start

    - name: Confirm Successful Trigger
      if: always()
      run: echo "✅ Triggered Successfully! Next Trigger in 6 Hours."
